### ISSUE TITLE
Zones can be created multiple times (api)

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#310]
If multiple requests are made fast enough you could create duplicate zones in the API. If the second request starts processing before the first request actually saves the zone in the database the second request will pass the "zoneDoesNotExist" check.

**Comment by pauljamescleary** [comment]
There will always be a race to the database for this issue.  The simplest thing to do is add a unique constraint to the zone table.  We have to anticipate this happening as we need to properly fail the zone change (as opposed to retrying it 100 times).

Some thoughts:
1. Add a flyway migration to add a unique constraint on zone.name
2. Update the `ZoneRepository.save(zone: Zone): IO[Zone]` to return an `EitherT[ZoneAlreadyExistsError, Zone]` instead.
3. Update the `ZoneChangeHandler` to anticipate the zone error, and mark the zone change as failed.

_Step 3_ is important, otherwise, the message will be retried 100 times and ultimately fail out.  We have to anticipate this as an error.

**Alternative**
We _could_ do a check in the `ZoneChangeHandler` prior to saving the zone and fail there, leaving the `ZoneRepository` as is.

Pros: Less changes are needed

Cons: We _still_ have the possibility for a race condition and the zone being saved multiple times, it is just a smaller window.

**Comment by britneywright** [comment]
I ended up going the ZoneChangeHandler route in my PR. Trying to change the save itself seemed to ripple out into a lot of required changes and it seemed to get out of hand with all the changes we make during the zone processing beyond just saving the zone itself.
