### ISSUE TITLE
Remove zoneID from getRecordSet 

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#353]
We require the user to enter the recordSetId and zoneId on getRecordSet, but we dont actually need or use the zoneId to get it from the database. Once we have the recordSet, we can pull the zoneId from there for any access considerations.

We should remove the zoneId from this call.

For backwards compatibility, if someone includes a zoneId in the request, we should just drop it (do not error).

Docs should also be updated accordingly.

**Comment by nimaeskandary** [comment]
It turns out we may need the zone id in the route given #638. We get the existing record from the payload recordset id and zone id, but there is no guarantee the zoneId in the payload is correct, thinking we need to be getting the existing record from the route zoneId and recordsetId, and validating the payload is not trying to change those things
