### ISSUE TITLE
Delete group logic

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#436]
Groups can be tied to record ownership, zone admin, and acl rules. Currently, the only validation done before deleting a group is that it is not set to be a zone admin group for any zones. It should be further discussed how we want to handle cases in which the group is set as a record owner, and when the group is used in an ACL rule

**Comment by pauljamescleary** [comment]
1. Group is deleted that is a record owner
The record set should be considered "unassigned"; log loudly this event (perhaps in the system message in addition to log)

2. The group is used in an ACL rule
- Could add a query on group deletion to see if the group is in the zone access table, this is a rather easy out.  Respond in the error message all ACL rules the group is mentioned in
- Instead of reject, could attempt to cleanup all Zone ACLs.  The downside is that you have to issue a zone update to all zones the group is used in and hope they all pass
- Finally, could skip this check all together, and have some kind of maintenance job that will align the ACL rules and groups.

**Comment by rebstar6** [comment]
see https://github.com/vinyldns/vinyldns/issues/311 as related

**Comment by nimaeskandary** [comment]
@pauljamescleary our get group and get groups in the dynamo repo already filter out deleted groups so think ACL rules should be fine since the logic would be the same. For record owner we have cards in progress/ merged that do not allow deleting a group if it is a record owner

**Comment by varsharun** [comment]
Fixed in #548
