### ISSUE TITLE
record change paging does not return all records

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#566]
**Describe the bug**
My guess this is because zone syncs makes all the record changes at the same time. Still unexpected though

**VinylDNS Version**
0.8.1-SNAPSHOT

**To Reproduce**
1. start up the api locally
1. connect to `dummy.` zone
1. `GET /zones/id/recordsetchanges?maxItems=1`
1. `GET /zones/id/recordsetchanges?maxItems=1&startFrom=prev.nextId`

No other records are found. If you make some record set adds, then it returns records when paging. So seems it has to do with the sync records all being made at the same time

**Comment by nimaeskandary** [comment]
This seems to be an issue faced from the DynamoDB implementation since it was seen from a local `api/reStart`, but investigating the sql code that repo likely has the same issue, given that we page by `created < startKey` and created is not unique in the sql table

**Comment by pauljamescleary** [comment]
The brute force fix for this is to change the SQL to use `LIMIT` and `OFFSET` instead of how it does paging now.  The reason we did paging (`LIMIT, OFFSET`) was due to how DynamoDB worked (there was no such thing as limit and offset in DynamoDB).

Additionally there were some performance benefits to using a sorted index, iirc with LIMIT and OFFSET, MySQL has to exercise the entire query and then apply the LIMIT clause.  With a sorted index and `x < column`, MySQL can apply the filter up front (or wherever optimal base on the query optimizer) and the query is significantly faster, especially for large result sets.
