### ISSUE TITLE
No way to view zone change history on deleted zone

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#617]
**Describe the bug**
The only endpoint we expose for zone changes is `/zones/:id/changes`. This endpoint starts by checking if the zone exists and if it doesn't it returns a 404. This makes it impossible to view the change history of a deleted zone.

Not sure if it speeds up performance by checking if the zone is there before querying dynamo, so maybe keep doing that and only don't if the user is a support user?

**VinylDNS Version**
0.9.2-SNAPSHOT

**Comment by britneywright** [comment]
what's the use case for wanting to see zone change history on a deleted zone?

**Comment by nimaeskandary** [comment]
Guess the idea is an auditor an admin should be able to see all changes to a zone and who made them, regardless of whether it is deleted or not, otherwise we wouldn't be saving zone changes after the zone is deleted

**Comment by britneywright** [comment]
is that more of a cleanup issues? perhaps we should be deleting zone changes when we delete a zone the way we're now deleting record sets.

**Comment by nimaeskandary** [comment]
We should verify with @rebstar6 or @pauljamescleary, but believe we want to keep those change histories forever regardless of zone deletes

**Comment by mitruly** [comment]
I agree with what @nimaeskandary is saying since all of our history tables provide an audit trail. An example is that in deleting record sets after zone abandon, we're not deleting the record set change history.

By keeping zone history, we can identify useful information like has this zone ever been connected to before, how many times has it been abandoned and reconnected to, etc.
