### ISSUE TITLE
read-only power user

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#74]
**Is your feature request related to a problem? Please describe.**
As far as user access in VinylDNS we have super users who can access and modify all data, or users who can modify groups and records based on group membership and ACL rules. Super user abilities are potentially destructive if not used correctly, so there's only a select few with that level of access. Unfortunately the lack of an in between makes it difficult to support users if you aren't a super user, and therefore cannot view their zones and groups.

**Describe the solution you'd like**
A read-only power user would have the ability to view all zones and groups but they would not be able to modify any of the data. We want users to make their own modifications but it's much easier to support them if we can see their configuration ourselves in VinylDNS when they need assistance.

**Comment by pauljamescleary** [comment]
I believe the only change that should be needed here is for `GET` endpoints.  All `GET` endpoints should allow access to the read-only power user.

There are a number of them, they all fall out in one of the `Services` somewhere.

The only "tricky" by-pass is when listing zones (which is not that tricky as there is already a path defined for super users).  I presume that the power user would be able to see _all_ zones.

**Comment by nimaeskandary** [comment]
This needs a new attribute on users, an existing data migration on current vinyl installations, and a protobuf change right? Really like the concept, will make support easier and safer, and will allow for auditors if they are desired by whoever has a vinyl installation

**Comment by pauljamescleary** [comment]
@nimaeskandary we do not protobuf users (because they were born in the portal).  So, we can just add the flag to the user table.  If it is not present, then default it to false.

The issue that does come to light here is that we need a way to make someone a readOnlyPowerUser.  Not sure how to do that at all.  We also do not have a way to make someone a vinyldns admin either.  So we should discuss that here.

**Comment by britneywright** [comment]
ah good points @pauljamescleary. I was thinking of using groups too. Like a super user group and a readOnly power user group to organize who has what abilities.

**Comment by pauljamescleary** [comment]
The simplest approach would be to use a group.  Since "super users" have access to all the things, they can manage that group.  The idea would be to have a "support user" group (I like support user rather than read-only power user for naming).  The support user group should be system defined / hard-coded (like named vinyldns-support).

We would have to do some tomfoolery in access validations however, to ask "isSupportUser" everywhere, that really just checks the user's groups.  In those validations, maybe a "flag" of some sort is preferable?

**Comment by rebstar6** [comment]
gotta think about the portal too btw

1st pass, this person probably cant see the full `manage zone` tab info because the logic for viewing is all or nothing on the ACL and connection info.

There will also have to be portal logic in there to show/hide the edit/delete buttons.

In general, assume both the api and portal have to know that this user is of that type, rather than checking a group, but the storage could potentially be by group

**Comment by rebstar6** [comment]
on the making, i do think it makes sense to give the site admins the power to give someone read only access. in the future, it may be nice to give them even more fine grained power (ACL!?!) so they can make someone a support user for a subset of zones, though i dont want to build out something like that til we need it.

the "how do we make admins in the 1st place" is still an open question for me

**Comment by mitruly** [comment]
I was actually thinking something along the lines of @rebstar6's zone-inclusive ACL rules as well.

Regarding the actual implementation, I am a bit indifferent to having a user flag vs group.

**Comment by pauljamescleary** [comment]
Did we decide on using a group?

For the portal, I would think that everything is available to support users, we would just make everything read only (except of course for things the user has access to).

For "how do we make someone an admin", we need a separate card.  I think we have a single "admin" for the system.  The admin has the ability to manage support users and that is about it (but we can talk about that on the other card.)

**Comment by rebstar6** [comment]
my portal point is that we cant ignore it - we have logic around what to show to each person (for example, do you show the update or delete buttons on the recordsets). Im not positive what this logic would do with this type of person if we make no portal changes.

**Comment by pauljamescleary** [comment]
Where the discussion I believe ended on this was to postpone the issue.

We need to thing through allowing read-only "any" access to users.

On the surface, there should be no issue with allowing all users to discover / see (read only) everything in the system.  From a UX standpoint, this has UI implications that need to be thought through.

Questions include:
1. How does a user see zones they cannot access?  Right now, the zones view shows only "my zones" that I have access to.  How does a user access other zones?  For example, a separate tab, a search filter, etc.
2. Are there any bits that we do not want read-only users to see.  For example, ACL rules.
3. Is a blanket read-only solution tenable?  Or do we need some "vinyldns admin" role for privilege management?

All to be discussed later.  Taking this out of discussion for the time being.

**Comment by britneywright** [comment]
## Initial
boolean on the user
treat all GETs as okay for read-only
keep PUTs for super users only

## Next
- API: add ability to enable/disable read-only user access (only super users can do it)
- update portal to determine what to show read-only users
