### ISSUE TITLE
Move jar creation inside Dockerfile

### ISSUE THREAD

**Issue by kasimon** [vinyldns/vinyldns#744]
(Probably related to #26)

**Is your feature request related to a problem? Please describe.**
I don't have sbt installed which prevents me from running the bin/docker-*.sh-Scripts. 

**Describe the solution you'd like**
If the api.jar was built inside a docker container, there would be not sbt tool needed on the host.

**Additional context**
I've come up with the following Dockerfile which builds the api docker image from "scratch" - needs only this file, run.sh and docker.conf. This looks much cleaner to me than the current solution.
 
```
FROM hseeberger/scala-sbt:8u212_1.2.8_2.12.8 as builder

RUN git clone -b 'v0.9.2' --single-branch --depth 1 https://github.com/vinyldns/vinyldns.git /vinyldns

RUN cd /vinyldns ; sbt api/assembly


FROM openjdk:8u201-jdk-alpine3.9

RUN apk add --update --no-cache netcat-openbsd bash

COPY --from=builder /vinyldns/modules/api/target/scala-2.12/vinyldns.jar /app/vinyldns-server.jar

COPY run.sh /app/run.sh
RUN chmod a+x /app/run.sh

COPY docker.conf /app/docker.conf

EXPOSE 9000
EXPOSE 2551

# set the entry point for the container to start vinyl, specify the config resource
ENTRYPOINT ["/app/run.sh"]

```

**Comment by pauljamescleary** [comment]
Thank you @kasimon for the issue.  The file `./bin/docker-up-vinyldns.sh` does not require sbt.

Is the idea to have a docker container that has sbt so you could run more scripts / builds without having everything installed locally?  Or are you only trying to start up vinyldns local?

**Comment by kasimon** [comment]
The resulting container does not contain sbt. There are two "FROM" parts in that dockerfile, the first creates the jar (with sbt) and the second copies the jar from the first. The first container then is discarded by docker. My main reason is that due to internal policy we try to build as much of our containers as we can in house instead of downloading them from the net. With the need to have sbt available is becomes more difficult.

**Comment by pauljamescleary** [comment]
Thanks @kasimon for the info.  As I understand it, you need to build the docker image in house. 

Food for thought on the docker file you have is that you are using `sbt api/assembly` which maybe removed in the future.  We are using sbt native packager to build the docker containers that we publish on public docker hub.  `sbt docker:stage` would create a similar folder structure to what is used in docker and then could use that instead of the jar file. 

Also, can't believe we still expose 2551, that really should go away as it is old.  Will make a note to clean that up as well.

**Comment by kasimon** [comment]
@pauljamescleary The main thing we are interested in is a well documented and easy to reproduce way to recreate the docker images as they can be found on docker hub. Having that would be awesome. The rest was only me poking around in the repository trying to build those images.

**Comment by pauljamescleary** [comment]
@kasimon That makes sense, the "without having sbt installed" is the key to that.  FYI, I pulled this to the top of our backlog for next sprint as I think it is straightforward.  Look for an update soon.

**Comment by pauljamescleary** [comment]
@kasimon are you looking to only build the docker images, or are you also looking to build the docker images _and_ run the func tests on them?

**Comment by pauljamescleary** [comment]
@kasimon I am starting to work on this.  The existing `docker/api` stuff is primarily used for running our func tests.  You mention that you just want to replicate the images on docker hub.

What we do today is use `sbt docker:publish` to publish those images.

I am going to post a PR that is similar to what you did.  Will rely on an `ENV` to pass in the version of vinyldns that you want to build as a tag.

Will ping you when it is up to see if that is what you were looking for.

**Comment by pauljamescleary** [comment]
@kasimon I posted an initial WIP https://github.com/vinyldns/vinyldns/pull/753, let me know your thoughts when you get a chance.

The `Dockerfile` has the ability to pass in the version of vinyldns (branch) that you want to build.  It also uses the same build as the public docker hub (using `sbt api/stage`).

I had to change the version of the base docker image for sbt; otherwise, the build downloads sbt which really defeats the purpose.  As a TODO, we need to update our sbt version

**Comment by pauljamescleary** [comment]
@kasimon This is now addressed.  We are wrapping up incorporating this into our normal release process.

In the meantime, you can checkout the `build` folder in the project root.  It has a few scripts, as well as a `README.md` in the same directory that provides guidance on how to run a release.

Let me know if you get a chance to test it out, would love for some feedback.

This should be our defacto release process very shortly.
