### ISSUE TITLE
VinylDNS Python Client

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#92]
**Background**
We have most of the makings of a good vinyldns python client in the functional tests at https://github.com/vinyldns/vinyldns/blob/master/modules/api/functional_test/vinyldns_python.py

With a little cleanup, this can be moved into the vinyldns-python repository and setup as a first class project.

**Scope of work**
* Port the vinyldns_python.py library to the vinyldns-python repository
* Clean up anything that is not-standard for python
* Add unit tests?  Unclear on how to unit test this, since it is just an API wrapper for vinyldns api
* Setup a release process (setup.py) to be able to build and release the project to pypi
* Add LICENSE and license headers
* Add a README on usage

**Comment by mitruly** [comment]
I think this is a good idea since it adds to the available tooling that can interact with VinylDNS.

> Add unit tests? Unclear on how to unit test this, since it is just an API wrapper for vinyldns api
Would testing be necessary beyond testing serialization and error handling? Mocking responses from the API would be tedious to create and manage.

> Setup a release process (setup.py) to be able to build and release the project to pypi
Do we currently upload any of the other tooling to their respective popular package managers? If we choose to do this, then we might want to make sure that the other tools do the same.

> Add LICENSE and license headers
With certain languages (eg. Javascript, etc.), the support for adding license headers is varied. We might consider generalizing our existing `bin/add-license-headers.sh` script so that headers can be added to tooling in a more automated fashion, since the headers for some tooling might currently be relying on copy + paste. This would also allow integrating header generation into their compile process if there are outside contributors.

**Comment by rebstar6** [comment]
i think port over what we have with the license headers and then treat it like any other project at that point...so add cards for all the other stuff above.

i dont think we need to figure out all of it before porting, it's fine to just have the cards there so that we (or someone else) can pick them up

--

on the unit test question, i would look at what nathan and mike have in place for their tools (if anything) and take that lead

**Comment by pauljamescleary** [comment]
For unit testing, the java client uses wiremock.  You can mock out API responses.  I think that is a fine approach, as everything would very fast, and there aren't a ton of endpoints to hit.

**Comment by pauljamescleary** [comment]
Moving this to https://github.com/vinyldns/vinyldns-python/issues/2
