### ISSUE TITLE
Any plans for supporting a Multi-Master environment?

### ISSUE THREAD

**Issue by majoros** [vinyldns/vinyldns#928]
Subject says it all. I have recently been put in charge of supporting a Multi-Master DNS environment.

**Comment by mitruly** [comment]
VinylDNS currently offers the flexibility to define DNS backends (https://www.vinyldns.io/operator/config-api#default-zone-connections) for zone connectivity which would allow you to define connection information at startup which would be linked to specific masters. Otherwise, the default zone connection would be used when connecting to a zone.

**Comment by pauljamescleary** [comment]
@majoros One major feature that has been under discussion for some time is zone management.  It requires us to get "closer" to the DNS backends (likely having providers for different DNS software).

If you have any thoughts about specific features you would like to see wrt multi-master please let us know.

**Comment by kontrolldkaos** [comment]
> VinylDNS currently offers the flexibility to define DNS backends (https://www.vinyldns.io/operator/config-api#default-zone-connections) for zone connectivity which would allow you to define connection information at startup which would be linked to specific masters. Otherwise, the default zone connection would be used when connecting to a zone.

As mitruly pointed out ..
You should be able to utilize what's currently available. Just need to ensure you're updating the backend hidden auth servers you want. You should only need to update one and the other will be updated due to how federation (MM) works. If one goes down, you just change config to use the active backend. We run federated servers in our environment and don't have any issues.

**Comment by remerle** [comment]
I feel that the DNS infrastructure should handle propagation across primary auth servers. If there's some specific need outside of synchronization that multi-master presents, we can open a specific issue.
